[package]
name = "ecs_kernel"
version = "0.1.0"
authors = ["Connor Wood <cwoodd@essex.ac.uk>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.3"
spin = "0.4.9"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dev-dependencies]
array-init = "0.0.3"
